/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_muhamad_hadi_saputra;

/**
 *
 * @author admin
 */
public class Muhamad_Hadi_S_FormAritmatika extends javax.swing.JFrame {
    //Inisiasi Tipe data aritmatika
    int nilai1, nilai2, hasil;

    /**
     * Creates new form Muhamad_Hadi_S_FormAritmatika
     */
    public Muhamad_Hadi_S_FormAritmatika() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnKali = new javax.swing.JButton();
        BtnBagi = new javax.swing.JButton();
        BtnSisaHasilBagi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        thasil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        tnilai1 = new javax.swing.JTextField();
        tnilai2 = new javax.swing.JTextField();
        BtnTambah = new javax.swing.JButton();
        BtnKurang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 510));
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        BtnKali.setText("*");
        BtnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKaliActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKali);
        BtnKali.setBounds(173, 236, 39, 30);

        BtnBagi.setText("/");
        BtnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBagiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBagi);
        BtnBagi.setBounds(245, 236, 37, 30);

        BtnSisaHasilBagi.setText("%");
        BtnSisaHasilBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSisaHasilBagiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSisaHasilBagi);
        BtnSisaHasilBagi.setBounds(313, 236, 43, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hasil");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 320, 30, 17);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 138, 26);

        thasil.setEditable(false);
        getContentPane().add(thasil);
        thasil.setBounds(150, 310, 141, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukan Nilai 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 85, 99, 17);

        keluar.setText("Exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(100, 430, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masukan Nilai 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 142, 99, 17);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(20, 430, 70, 30);
        getContentPane().add(tnilai1);
        tnilai1.setBounds(152, 85, 160, 30);
        getContentPane().add(tnilai2);
        tnilai2.setBounds(150, 140, 160, 30);

        BtnTambah.setText("+");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTambah);
        BtnTambah.setBounds(23, 236, 41, 30);

        BtnKurang.setText("-");
        BtnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKurangActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKurang);
        BtnKurang.setBounds(96, 236, 37, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bg_4.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 2880, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKurangActionPerformed
        // TODO add your handling code here:
        nilai1 = Integer.valueOf(tnilai1.getText());
        nilai2 = Integer.valueOf(tnilai2.getText());
        hasil  = nilai1-nilai2;
        thasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BtnKurangActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // penjumlahan
        nilai1 = Integer.valueOf(tnilai1.getText());
        nilai2 = Integer.valueOf(tnilai2.getText());
        hasil  = nilai1+nilai2;
        thasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        tnilai1.setText("");
        tnilai2.setText("");
        thasil.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void BtnSisaHasilBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSisaHasilBagiActionPerformed
        // TODO add your handling code here:
        nilai1 = Integer.valueOf(tnilai1.getText());
        nilai2 = Integer.valueOf(tnilai2.getText());
        hasil  = nilai1%nilai2;
        thasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BtnSisaHasilBagiActionPerformed

    private void BtnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBagiActionPerformed
        // TODO add your handling code here:
        nilai1 = Integer.valueOf(tnilai1.getText());
        nilai2 = Integer.valueOf(tnilai2.getText());
        hasil  = nilai1/nilai2;
        thasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BtnBagiActionPerformed

    private void BtnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKaliActionPerformed
        // TODO add your handling code here:
        nilai1 = Integer.valueOf(tnilai1.getText());
        nilai2 = Integer.valueOf(tnilai2.getText());
        hasil  = nilai1*nilai2;
        thasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BtnKaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Muhamad_Hadi_S_FormAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBagi;
    private javax.swing.JButton BtnKali;
    private javax.swing.JButton BtnKurang;
    private javax.swing.JButton BtnSisaHasilBagi;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton keluar;
    private javax.swing.JButton reset;
    private javax.swing.JTextField thasil;
    private javax.swing.JTextField tnilai1;
    private javax.swing.JTextField tnilai2;
    // End of variables declaration//GEN-END:variables
}
