/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_muhamad_hadi_saputra;

import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;


/**
 *
 * @author admin
 */
public class Muhamad_Hadi_S_FormMenu extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Muhamad_Hadi_S_FormMenu
     */
    public Muhamad_Hadi_S_FormMenu() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    new Thread()
    {
      public void run()
      {
        for (;;)
        {
          Calendar kalender = new GregorianCalendar();
          int tahun = kalender.get(1);
          int bulan = kalender.get(2);
          int hari = kalender.get(5);
          int jam = kalender.get(11);
          int menit = kalender.get(12);
          int detik = kalender.get(13);
          String tanggal = hari + "/" + bulan + "/" + tahun;
          String waktu = jam + " : " + menit + " : " + detik;
          Muhamad_Hadi_S_FormMenu.this.tanggal.setText(waktu);
          Muhamad_Hadi_S_FormMenu.this.waktu.setText(tanggal);
        }
      }
    }.start();
      
    }
     public static boolean openWebpage(URI uri)
  {
    Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
    if ((desktop != null) && (desktop.isSupported(Desktop.Action.BROWSE))) {
      try
      {
        desktop.browse(uri);
        return true;
      }
      catch (Exception e)
      {
        e.printStackTrace();
      }
    }
    return false;
  }
  
  public static boolean openWebpage(URL url)
  {
    try
    {
      return openWebpage(url.toURI());
    }
    catch (URISyntaxException e)
    {
      e.printStackTrace();
    }
    return false;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mulai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        bpengembang = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        PAritmatika = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        Ppersergipanjang = new javax.swing.JMenuItem();
        PPersegi = new javax.swing.JMenuItem();
        PJajargenjang = new javax.swing.JMenuItem();
        PLingkaran = new javax.swing.JMenuItem();
        PSegitiga = new javax.swing.JMenuItem();
        penugasan = new javax.swing.JMenuItem();
        logika = new javax.swing.JMenuItem();
        relasi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        CPTernary1 = new javax.swing.JMenuItem();
        CPTernary2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuif = new javax.swing.JMenu();
        if1 = new javax.swing.JMenuItem();
        if2 = new javax.swing.JMenuItem();
        menuifelse = new javax.swing.JMenu();
        ifelse1 = new javax.swing.JMenuItem();
        ifelse2 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        ifelseif1 = new javax.swing.JMenuItem();
        ifelseif2 = new javax.swing.JMenuItem();
        mswitch = new javax.swing.JMenu();
        switch1 = new javax.swing.JMenuItem();
        switch2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        For1 = new javax.swing.JMenu();
        for1 = new javax.swing.JMenuItem();
        For2 = new javax.swing.JMenuItem();
        for3 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        while1 = new javax.swing.JMenuItem();
        while2 = new javax.swing.JMenuItem();
        while3 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        dowhile1 = new javax.swing.JMenuItem();
        dowhile2 = new javax.swing.JMenuItem();
        dowhile3 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        aray1d1 = new javax.swing.JMenuItem();
        aray1d2 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        array2d1 = new javax.swing.JMenuItem();
        array2d2 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        procedure = new javax.swing.JMenuItem();
        method = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        koneksi = new javax.swing.JMenuItem();
        biodb = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/IconComputer.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(jPanel1);
        jLabel2.setText("PEMROGRAMAN BERORIENTASI OBJEK");

        mulai.setText("MULAI");
        mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(mulai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(mulai)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/netbeansicon.png"))); // NOI18N

        waktu.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        waktu.setText("jLabel4");

        tanggal.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tanggal.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("021200015 - Muhamad Hadi Saputra");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconwindows.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(waktu)
                        .addGap(135, 135, 135)
                        .addComponent(tanggal)
                        .addGap(116, 116, 116))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waktu)
                            .addComponent(tanggal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addGap(30, 30, 30))
        );

        jMenu5.setText("Dasar");

        jMenuItem5.setText("Visual");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        bpengembang.setText("Biodata Pengembang");
        bpengembang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengembangActionPerformed(evt);
            }
        });
        jMenu5.add(bpengembang);

        jMenuBar3.add(jMenu5);

        jMenu6.setText("Operator");

        PAritmatika.setText("Program Aritmatika");
        PAritmatika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAritmatikaActionPerformed(evt);
            }
        });
        jMenu6.add(PAritmatika);

        jMenu8.setText("Program Bangun Datar");

        Ppersergipanjang.setText("Program Persegi Panjang");
        Ppersergipanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PpersergipanjangActionPerformed(evt);
            }
        });
        jMenu8.add(Ppersergipanjang);

        PPersegi.setText("Program Persegi");
        PPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPersegiActionPerformed(evt);
            }
        });
        jMenu8.add(PPersegi);

        PJajargenjang.setText("Program Jajar Genjang");
        PJajargenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJajargenjangActionPerformed(evt);
            }
        });
        jMenu8.add(PJajargenjang);

        PLingkaran.setText("Program Lingkaran");
        PLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLingkaranActionPerformed(evt);
            }
        });
        jMenu8.add(PLingkaran);

        PSegitiga.setText("Program Segitiga");
        PSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSegitigaActionPerformed(evt);
            }
        });
        jMenu8.add(PSegitiga);

        jMenu6.add(jMenu8);

        penugasan.setText("Program Penugasan");
        penugasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penugasanActionPerformed(evt);
            }
        });
        jMenu6.add(penugasan);

        logika.setText("Program Logika");
        logika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logikaActionPerformed(evt);
            }
        });
        jMenu6.add(logika);

        relasi.setText("Program Relasi");
        relasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relasiActionPerformed(evt);
            }
        });
        jMenu6.add(relasi);

        jMenu1.setText("Program Ternary");

        CPTernary1.setText("Contoh Program 1");
        CPTernary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPTernary1ActionPerformed(evt);
            }
        });
        jMenu1.add(CPTernary1);

        CPTernary2.setText("Contoh Program 2");
        CPTernary2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPTernary2ActionPerformed(evt);
            }
        });
        jMenu1.add(CPTernary2);

        jMenu6.add(jMenu1);

        jMenuBar3.add(jMenu6);

        jMenu7.setText("Percabangan");

        menuif.setText("IF");

        if1.setText("Contoh 1");
        if1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if1ActionPerformed(evt);
            }
        });
        menuif.add(if1);

        if2.setText("Contoh 2");
        if2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if2ActionPerformed(evt);
            }
        });
        menuif.add(if2);

        jMenu7.add(menuif);

        menuifelse.setText("IF..Else");

        ifelse1.setText("Contoh 1");
        ifelse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifelse1ActionPerformed(evt);
            }
        });
        menuifelse.add(ifelse1);

        ifelse2.setText("Contoh 2");
        ifelse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifelse2ActionPerformed(evt);
            }
        });
        menuifelse.add(ifelse2);

        jMenu7.add(menuifelse);

        jMenu11.setText("IF..Else IF");

        ifelseif1.setText("Contoh 1");
        ifelseif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifelseif1ActionPerformed(evt);
            }
        });
        jMenu11.add(ifelseif1);

        ifelseif2.setText("Contoh 2");
        ifelseif2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifelseif2ActionPerformed(evt);
            }
        });
        jMenu11.add(ifelseif2);

        jMenu7.add(jMenu11);

        mswitch.setText("Switch");

        switch1.setText("Contoh 1");
        switch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch1ActionPerformed(evt);
            }
        });
        mswitch.add(switch1);

        switch2.setText("Contoh 2");
        switch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch2ActionPerformed(evt);
            }
        });
        mswitch.add(switch2);

        jMenu7.add(mswitch);

        jMenuBar3.add(jMenu7);

        jMenu9.setText("Perulangan");

        For1.setText("For");

        for1.setText("Contoh 1");
        for1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for1ActionPerformed(evt);
            }
        });
        For1.add(for1);

        For2.setText("Contoh 2");
        For2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                For2ActionPerformed(evt);
            }
        });
        For1.add(For2);

        for3.setText("Contoh 3");
        for3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for3ActionPerformed(evt);
            }
        });
        For1.add(for3);

        jMenu9.add(For1);

        jMenu14.setText("While");

        while1.setText("Contoh 1");
        while1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                while1ActionPerformed(evt);
            }
        });
        jMenu14.add(while1);

        while2.setText("Contoh 2");
        while2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                while2ActionPerformed(evt);
            }
        });
        jMenu14.add(while2);

        while3.setText("Contoh 3");
        while3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                while3ActionPerformed(evt);
            }
        });
        jMenu14.add(while3);

        jMenu9.add(jMenu14);

        jMenu15.setText("Do While");

        dowhile1.setText("Contoh 1");
        dowhile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dowhile1ActionPerformed(evt);
            }
        });
        jMenu15.add(dowhile1);

        dowhile2.setText("Contoh 2");
        dowhile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dowhile2ActionPerformed(evt);
            }
        });
        jMenu15.add(dowhile2);

        dowhile3.setText("Contoh 3");
        dowhile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dowhile3ActionPerformed(evt);
            }
        });
        jMenu15.add(dowhile3);

        jMenu9.add(jMenu15);

        jMenuBar3.add(jMenu9);

        jMenu10.setText("Array");

        jMenu16.setText("Satu Dimensi");

        aray1d1.setText("Contoh 1");
        aray1d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aray1d1ActionPerformed(evt);
            }
        });
        jMenu16.add(aray1d1);

        aray1d2.setText("Contoh 2");
        aray1d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aray1d2ActionPerformed(evt);
            }
        });
        jMenu16.add(aray1d2);

        jMenu10.add(jMenu16);

        jMenu17.setText("Dua Dimensi");

        array2d1.setText("Contoh 1");
        array2d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                array2d1ActionPerformed(evt);
            }
        });
        jMenu17.add(array2d1);

        array2d2.setText("Contoh 2");
        array2d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                array2d2ActionPerformed(evt);
            }
        });
        jMenu17.add(array2d2);

        jMenu10.add(jMenu17);

        jMenuBar3.add(jMenu10);

        jMenu12.setText("OOP");

        procedure.setText("Procedure ");
        procedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedureActionPerformed(evt);
            }
        });
        jMenu12.add(procedure);

        method.setText("Method ");
        method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodActionPerformed(evt);
            }
        });
        jMenu12.add(method);

        jMenuItem36.setText("This");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem36);

        jMenuItem37.setText("Constructor");
        jMenu12.add(jMenuItem37);

        jMenuItem38.setText("Inheritence");
        jMenu12.add(jMenuItem38);

        jMenuItem39.setText("PolyMorphism");
        jMenu12.add(jMenuItem39);

        jMenuItem40.setText("Encapsulation");
        jMenu12.add(jMenuItem40);

        jMenuBar3.add(jMenu12);

        jMenu13.setText("Database");

        koneksi.setText("Koneksi admin & user");
        koneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koneksiActionPerformed(evt);
            }
        });
        jMenu13.add(koneksi);

        biodb.setText("Biodata");
        biodb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biodbActionPerformed(evt);
            }
        });
        jMenu13.add(biodb);
        jMenu13.add(jSeparator1);

        jMenuItem43.setText("Report");
        jMenu13.add(jMenuItem43);

        jMenuBar3.add(jMenu13);

        jMenu2.setText("HelpNDoc");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar3.add(jMenu2);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PAritmatikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAritmatikaActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormAritmatika faritmatika = new  Muhamad_Hadi_S_FormAritmatika();
        faritmatika.show();

    }//GEN-LAST:event_PAritmatikaActionPerformed

    private void PpersergipanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PpersergipanjangActionPerformed
        // Action pindah ke form persegi panjang:
         Muhamad_Hadi_S_FormPersegiPanjang fpersegipanjang = new  Muhamad_Hadi_S_FormPersegiPanjang();
         fpersegipanjang.show();

    }//GEN-LAST:event_PpersergipanjangActionPerformed

    private void PPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPersegiActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormPersegi fpersegi = new  Muhamad_Hadi_S_FormPersegi();
        fpersegi.show();

    }//GEN-LAST:event_PPersegiActionPerformed

    private void PJajargenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJajargenjangActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormJajarGenjang fjajargenjang = new  Muhamad_Hadi_S_FormJajarGenjang();
         fjajargenjang.show();

    }//GEN-LAST:event_PJajargenjangActionPerformed

    private void PLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLingkaranActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormLingkaran flingkaran = new  Muhamad_Hadi_S_FormLingkaran();
        flingkaran.show();

    }//GEN-LAST:event_PLingkaranActionPerformed

    private void PSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSegitigaActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormSegitiga fsegitiga = new  Muhamad_Hadi_S_FormSegitiga();
         fsegitiga.show();

    }//GEN-LAST:event_PSegitigaActionPerformed

    private void if1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_if1ActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_Ifthen1 fifthen1 = new  Muhamad_Hadi_S_Ifthen1();
         fifthen1.show();

    }//GEN-LAST:event_if1ActionPerformed

    private void ifelse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifelse1ActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormIfthenelse1 fifthenelse1 = new  Muhamad_Hadi_S_FormIfthenelse1();
         fifthenelse1.show();
    }//GEN-LAST:event_ifelse1ActionPerformed

    private void switch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch1ActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormSwitch1 fswitch1 = new Muhamad_Hadi_S_FormSwitch1();
         fswitch1.show();

    }//GEN-LAST:event_switch1ActionPerformed

    private void switch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch2ActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormSwitch2 fswitch2 = new Muhamad_Hadi_S_FormSwitch2();
         fswitch2.show();
    }//GEN-LAST:event_switch2ActionPerformed

    private void for1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for1ActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormFor1 ffor1 = new Muhamad_Hadi_S_FormFor1();
         ffor1.show();

    }//GEN-LAST:event_for1ActionPerformed

    private void For2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_For2ActionPerformed
        // TODO add your handling code here:
          Muhamad_Hadi_S_FormFor2 ffor2 = new Muhamad_Hadi_S_FormFor2();
         ffor2.show();

    }//GEN-LAST:event_For2ActionPerformed

    private void while1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_while1ActionPerformed
        // TODO add your handling code here:
          Muhamad_Hadi_S_FormWhile1 fwhile1 = new Muhamad_Hadi_S_FormWhile1();
         fwhile1.show();

    }//GEN-LAST:event_while1ActionPerformed

    private void while2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_while2ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormWhile2 fwhile2 = new Muhamad_Hadi_S_FormWhile2();
         fwhile2.show();

    }//GEN-LAST:event_while2ActionPerformed

    private void dowhile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dowhile1ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormDoWhile1 fdowhile1 = new Muhamad_Hadi_S_FormDoWhile1();
         fdowhile1.show();

    }//GEN-LAST:event_dowhile1ActionPerformed

    private void dowhile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dowhile2ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormDoWhile2 fdowhile2 = new Muhamad_Hadi_S_FormDoWhile2();
         fdowhile2.show();

    }//GEN-LAST:event_dowhile2ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void biodbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biodbActionPerformed
        // TODO add your handling code here:
          Muhamad_Hadi_FormBiodataKoneksiDB fbiodb = new Muhamad_Hadi_FormBiodataKoneksiDB();
         fbiodb.show();
    }//GEN-LAST:event_biodbActionPerformed

    private void mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Selamat Datang, Silahkan pilih menu diatas yang ingin dijalankan!");
    }//GEN-LAST:event_mulaiActionPerformed

    private void CPTernary2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPTernary2ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormTernary2 fternary2 = new  Muhamad_Hadi_S_FormTernary2();
         fternary2.show();
    }//GEN-LAST:event_CPTernary2ActionPerformed

    private void CPTernary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPTernary1ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormTernary1 fternary1 = new  Muhamad_Hadi_S_FormTernary1();
         fternary1.show();
        
    }//GEN-LAST:event_CPTernary1ActionPerformed

    private void if2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_if2ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_Ifthen2 fifthen2 = new  Muhamad_Hadi_S_Ifthen2();
         fifthen2.show();
    }//GEN-LAST:event_if2ActionPerformed

    private void ifelseif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifelseif1ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormIfthenelseIf1 fifthenelseif1 = new  Muhamad_Hadi_S_FormIfthenelseIf1();
         fifthenelseif1.show();
        
    }//GEN-LAST:event_ifelseif1ActionPerformed

    private void ifelse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifelse2ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormIfthenelse2 fifthenelse2 = new  Muhamad_Hadi_S_FormIfthenelse2();
         fifthenelse2.show();
        
    }//GEN-LAST:event_ifelse2ActionPerformed

    private void ifelseif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifelseif2ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormIfthenelseIf2 fifthenelseif2 = new  Muhamad_Hadi_S_FormIfthenelseIf2();
         fifthenelseif2.show();
        
    }//GEN-LAST:event_ifelseif2ActionPerformed

    private void bpengembangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengembangActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormDasarKreasi fdasarkreasi = new  Muhamad_Hadi_S_FormDasarKreasi();
         fdasarkreasi.show();
    }//GEN-LAST:event_bpengembangActionPerformed

    private void penugasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penugasanActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormPenugasan fpenugasan = new  Muhamad_Hadi_S_FormPenugasan();
         fpenugasan.show();
    }//GEN-LAST:event_penugasanActionPerformed

    private void logikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logikaActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormLogika flogika = new  Muhamad_Hadi_S_FormLogika();
         flogika.show();
    }//GEN-LAST:event_logikaActionPerformed

    private void relasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relasiActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormRelasi frelasi = new  Muhamad_Hadi_S_FormRelasi();
         frelasi.show();
    }//GEN-LAST:event_relasiActionPerformed

    private void for3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for3ActionPerformed
        // TODO add your handling code here:
          Muhamad_Hadi_S_FormFor3 ffor3 = new Muhamad_Hadi_S_FormFor3();
         ffor3.show();
    }//GEN-LAST:event_for3ActionPerformed

    private void while3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_while3ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormWhile3 fwhile3 = new Muhamad_Hadi_S_FormWhile3();
         fwhile3.show();
    }//GEN-LAST:event_while3ActionPerformed

    private void dowhile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dowhile3ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormDoWhile3 fdowhile3 = new Muhamad_Hadi_S_FormDoWhile3();
         fdowhile3.show();
    }//GEN-LAST:event_dowhile3ActionPerformed

    private void aray1d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aray1d1ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormArray1Dimensi1 faray1d1 = new Muhamad_Hadi_S_FormArray1Dimensi1();
         faray1d1.show();
    }//GEN-LAST:event_aray1d1ActionPerformed

    private void aray1d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aray1d2ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormArray1Dimensi2 faray1d2 = new Muhamad_Hadi_S_FormArray1Dimensi2();
         faray1d2.show();
    }//GEN-LAST:event_aray1d2ActionPerformed

    private void array2d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_array2d1ActionPerformed
        // TODO add your handling code here:
         Muhamad_Hadi_S_FormArray2Dimensi1 faray2d1 = new Muhamad_Hadi_S_FormArray2Dimensi1();
         faray2d1.show();
    }//GEN-LAST:event_array2d1ActionPerformed

    private void array2d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_array2d2ActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormArray2Dimensi2 faray2d2 = new Muhamad_Hadi_S_FormArray2Dimensi2();
         faray2d2.show();
                        
    }//GEN-LAST:event_array2d2ActionPerformed

    private void procedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedureActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormDataMahasiswa fformdatam = new Muhamad_Hadi_S_FormDataMahasiswa();
         fformdatam.show();
                       
    }//GEN-LAST:event_procedureActionPerformed

    private void methodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_InputKeyboard finputk = new Muhamad_Hadi_S_InputKeyboard();
         finputk.show();
                       
    }//GEN-LAST:event_methodActionPerformed

    private void koneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koneksiActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_FormUser fuser = new Muhamad_Hadi_S_FormUser();
        fuser.show();
        JOptionPane.showMessageDialog(null, "Silahkan Hidupkan localserver xampp!" );
       
        
    }//GEN-LAST:event_koneksiActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
           openWebpage(URI.create("https://google.com"));
           JOptionPane.showMessageDialog(null, "Silahkan Hidupkan localserver xampp!" );
           
           
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Muhamad_Hadi_S_Visual fuser = new Muhamad_Hadi_S_Visual();
        fuser.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Muhamad_Hadi_S_FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Muhamad_Hadi_S_FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CPTernary1;
    private javax.swing.JMenuItem CPTernary2;
    private javax.swing.JMenu For1;
    private javax.swing.JMenuItem For2;
    private javax.swing.JMenuItem PAritmatika;
    private javax.swing.JMenuItem PJajargenjang;
    private javax.swing.JMenuItem PLingkaran;
    private javax.swing.JMenuItem PPersegi;
    private javax.swing.JMenuItem PSegitiga;
    private javax.swing.JMenuItem Ppersergipanjang;
    private javax.swing.JMenuItem aray1d1;
    private javax.swing.JMenuItem aray1d2;
    private javax.swing.JMenuItem array2d1;
    private javax.swing.JMenuItem array2d2;
    private javax.swing.JMenuItem biodb;
    private javax.swing.JMenuItem bpengembang;
    private javax.swing.JMenuItem dowhile1;
    private javax.swing.JMenuItem dowhile2;
    private javax.swing.JMenuItem dowhile3;
    private javax.swing.JMenuItem for1;
    private javax.swing.JMenuItem for3;
    private javax.swing.JMenuItem if1;
    private javax.swing.JMenuItem if2;
    private javax.swing.JMenuItem ifelse1;
    private javax.swing.JMenuItem ifelse2;
    private javax.swing.JMenuItem ifelseif1;
    private javax.swing.JMenuItem ifelseif2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem koneksi;
    private javax.swing.JMenuItem logika;
    private javax.swing.JMenu menuif;
    private javax.swing.JMenu menuifelse;
    private javax.swing.JMenuItem method;
    private javax.swing.JMenu mswitch;
    private javax.swing.JButton mulai;
    private javax.swing.JMenuItem penugasan;
    private javax.swing.JMenuItem procedure;
    private javax.swing.JMenuItem relasi;
    private javax.swing.JMenuItem switch1;
    private javax.swing.JMenuItem switch2;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel waktu;
    private javax.swing.JMenuItem while1;
    private javax.swing.JMenuItem while2;
    private javax.swing.JMenuItem while3;
    // End of variables declaration//GEN-END:variables
}
